<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-11-05 20:29:47 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of 'Author' documents,
then the 'AuthorDocument' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Product\Base;

use Dat0r\Core\Document;

/**
 * Serves as the base class to the 'Author' document skeleton.
 */
abstract class AuthorDocument extends Document\Document
{
    /**
     * Returns an 'Author' document's first_name.
     *
     * @return 
     */
    public function getFirstName()
    {
        return $this->getValue('first_name');
    }

    /**
     * Sets an 'Author' document's first_name.
     *
     * @param  $first_name
     */
    public function setFirstName($first_name)
    {
        $this->setValue('first_name', $first_name);
    }

    /**
     * Returns an 'Author' document's last_name.
     *
     * @return 
     */
    public function getLastName()
    {
        return $this->getValue('last_name');
    }

    /**
     * Sets an 'Author' document's last_name.
     *
     * @param  $last_name
     */
    public function setLastName($last_name)
    {
        $this->setValue('last_name', $last_name);
    }
}
