<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-11-05 20:29:47 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of the 'Author' module,
then the 'AuthorModule' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Product\Base;

use Dat0r\Core\Field\TextField;
use Dat0r\Core\Module;

/**
 * Serves as the base class to the 'Author'' module skeleton.
 */
abstract class AuthorModule extends Module\AggregateModule
{
    /**
     * Creates a new AuthorModule instance.
     */
    protected function __construct()
    {
        parent::__construct(
            'Author',
            array(
                TextField::create(
                    'first_name',
                    array()
                ),
                TextField::create(
                    'last_name',
                    array()
                ),
            ),
            array()
        );
    }

    /**
     * Returns the IDocument implementor to use when creating new documents.
     *
     * @return string Fully qualified name of an IDocument implementation.
     */
    protected function getDocumentImplementor()
    {
        return '\\Honeybee\\Domain\\Product\\AuthorDocument';
    }
}
