<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-11-05 20:29:47 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of the 'Product' module,
then the 'ProductModule' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Product\Base;

use Dat0r\Core\Field\AggregateField;
use Dat0r\Core\Field\IntegerCollectionField;
use Dat0r\Core\Field\KeyValueField;
use Dat0r\Core\Field\TextField;
use Honeybee\Core\Dat0r;

/**
 * Serves as the base class to the 'Product'' module skeleton.
 */
abstract class ProductModule extends Dat0r\Module
{
    /**
     * Creates a new ProductModule instance.
     */
    protected function __construct()
    {
        parent::__construct(
            'Product',
            array(
                TextField::create(
                    'id',
                    array(
                        'mandatory' => true,
                    )
                ),
                TextField::create(
                    'title',
                    array()
                ),
                IntegerCollectionField::create(
                    'pdf_files',
                    array(
                        'max' => 200,
                        'acts_as_asset_field' => true,
                    )
                ),
                AggregateField::create(
                    'authors',
                    array(
                        'modules' => array(
                            '\\Honeybee\\Domain\\Product\\AuthorModule',
                        ),
                    )
                ),
                AggregateField::create(
                    'offers',
                    array(
                        'modules' => array(
                            '\\Honeybee\\Domain\\Product\\OfferModule',
                        ),
                    )
                ),
                KeyValueField::create(
                    'meta',
                    array(
                        'constraints' => array(
                            'value_type' => 'dynamic',
                        ),
                    )
                ),
                AggregateField::create(
                    'workflowTicket',
                    array(
                        'modules' => array(
                            '\\Honeybee\\Domain\\Product\\WorkflowTicketModule',
                        ),
                    )
                ),
            ),
            array(
                'prefix' => 'product',
                'identifier_field' => 'identifier',
                'slugPattern' => 'product-{shortId}',
            )
        );
    }

    /**
     * Returns the IDocument implementor to use when creating new documents.
     *
     * @return string Fully qualified name of an IDocument implementation.
     */
    protected function getDocumentImplementor()
    {
        return '\\Honeybee\\Domain\\Product\\ProductDocument';
    }
}
