<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-11-05 20:29:47 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of 'Product' documents,
then the 'ProductDocument' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Product\Base;

use Honeybee\Core\Dat0r;

/**
 * Serves as the base class to the 'Product' document skeleton.
 */
abstract class ProductDocument extends Dat0r\Document
{
    /**
     * Returns an 'Product' document's id.
     *
     * @return 
     */
    public function getId()
    {
        return $this->getValue('id');
    }

    /**
     * Sets an 'Product' document's id.
     *
     * @param  $id
     */
    public function setId($id)
    {
        $this->setValue('id', $id);
    }

    /**
     * Returns an 'Product' document's title.
     *
     * @return 
     */
    public function getTitle()
    {
        return $this->getValue('title');
    }

    /**
     * Sets an 'Product' document's title.
     *
     * @param  $title
     */
    public function setTitle($title)
    {
        $this->setValue('title', $title);
    }

    /**
     * Returns an 'Product' document's pdf_files.
     *
     * @return 
     */
    public function getPdfFiles()
    {
        return $this->getValue('pdf_files');
    }

    /**
     * Sets an 'Product' document's pdf_files.
     *
     * @param  $pdf_files
     */
    public function setPdfFiles($pdf_files)
    {
        $this->setValue('pdf_files', $pdf_files);
    }

    /**
     * Returns an 'Product' document's authors.
     *
     * @return 
     */
    public function getAuthors()
    {
        return $this->getValue('authors');
    }

    /**
     * Sets an 'Product' document's authors.
     *
     * @param  $authors
     */
    public function setAuthors($authors)
    {
        $this->setValue('authors', $authors);
    }

    /**
     * Returns an 'Product' document's offers.
     *
     * @return 
     */
    public function getOffers()
    {
        return $this->getValue('offers');
    }

    /**
     * Sets an 'Product' document's offers.
     *
     * @param  $offers
     */
    public function setOffers($offers)
    {
        $this->setValue('offers', $offers);
    }

    /**
     * Returns an 'Product' document's meta.
     *
     * @return 
     */
    public function getMeta()
    {
        return $this->getValue('meta');
    }

    /**
     * Sets an 'Product' document's meta.
     *
     * @param  $meta
     */
    public function setMeta($meta)
    {
        $this->setValue('meta', $meta);
    }

    /**
     * Returns an 'Product' document's workflowTicket.
     *
     * @return 
     */
    public function getWorkflowTicket()
    {
        return $this->getValue('workflowTicket');
    }

    /**
     * Sets an 'Product' document's workflowTicket.
     *
     * @param  $workflowTicket
     */
    public function setWorkflowTicket($workflowTicket)
    {
        $this->setValue('workflowTicket', $workflowTicket);
    }
}
