<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-11-05 20:29:47 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of the 'WorkflowTicket' module,
then the 'WorkflowTicketModule' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Product\Base;

use Dat0r\Core\Field\AggregateField;
use Dat0r\Core\Field\BooleanField;
use Dat0r\Core\Field\KeyValueField;
use Dat0r\Core\Field\TextField;
use Dat0r\Core\Module;

/**
 * Serves as the base class to the 'WorkflowTicket'' module skeleton.
 */
abstract class WorkflowTicketModule extends Module\AggregateModule
{
    /**
     * Creates a new WorkflowTicketModule instance.
     */
    protected function __construct()
    {
        parent::__construct(
            'WorkflowTicket',
            array(
                TextField::create(
                    'workflowName',
                    array()
                ),
                TextField::create(
                    'workflowStep',
                    array()
                ),
                TextField::create(
                    'owner',
                    array()
                ),
                BooleanField::create(
                    'blocked',
                    array()
                ),
                TextField::create(
                    'waitUntil',
                    array()
                ),
                KeyValueField::create(
                    'stepCounts',
                    array(
                        'constraints' => array(
                            'value_type' => 'integer',
                        ),
                    )
                ),
                AggregateField::create(
                    'lastResult',
                    array(
                        'modules' => array(
                            '\\Honeybee\\Domain\\Product\\PluginResultModule',
                        ),
                    )
                ),
            ),
            array()
        );
    }

    /**
     * Returns the IDocument implementor to use when creating new documents.
     *
     * @return string Fully qualified name of an IDocument implementation.
     */
    protected function getDocumentImplementor()
    {
        return '\\Honeybee\\Domain\\Product\\WorkflowTicketDocument';
    }
}
