<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-11-05 20:29:47 and allows to alter the behaviour of 'Offer' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Product;

use Honeybee\Domain\Product\Base;

/**
 * ...
 */
class OfferDocument extends Base\OfferDocument
{

}
