<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-11-05 20:29:47 and allows to alter the behaviour of the 'Offer' module.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Product;

use Honeybee\Domain\Product\Base;

/**
 * The OfferModule class reflects the declared structure of the 'Offer' entity.
 * It holds the meta data necessary to manage/initiate 'OfferDocument' lifecycles.
 */
class OfferModule extends Base\OfferModule
{

}
